apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-matcher
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Disable scale to zero with a min scale of 1.
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/initial-scale: "0"
        # Limit scaling to 100 pods.
#        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/max-scale: "10"
        autoscaling.knative.dev/target-utilization-percentage: "100"
#        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/window: "120s"
#        autoscaling.knative.dev/window: "6s"
    spec:
      containerConcurrency: 1
      schedulerName: gpushare-scheduler
      containers:
        - image: 192.168.10.82:5000/feature-matcher-gpu:v3.0
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
          name: feature-matcher
#          resources:
#            limits:
#              # GiB
#              ucloud.cn/gpu-mem: "1"
          volumeMounts:
            - mountPath: /home/data/
              name: reid
      volumes:
        - name: reid
          persistentVolumeClaim:
            claimName: reid-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - "true"
