apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: feature-extractor
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "40"
        # Disable scale to zero with a min scale of 1.
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/initial-scale: "1"
        # Limit scaling to 100 pods.
        autoscaling.knative.dev/max-scale: "5"
        autoscaling.knative.dev/scale-down-delay: "40s"
    spec:
      schedulerName: gpushare-scheduler
      containerConcurrency: 40
      containers:
        - image: 192.168.10.82:5000/feature-extractor-gpu:v3.0
          ports:
            - containerPort: 6001
          imagePullPolicy: IfNotPresent
          name: feature-extractor
#          resources:
#            limits:
#              # GiB
#              ucloud.cn/gpu-mem: "1"
          volumeMounts:
            - mountPath: /home/data/
              name: reid
      volumes:
        - name: reid
          persistentVolumeClaim:
            claimName: reid-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - "true"
