apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: front-end
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "20"
        # Disable scale to zero with a min scale of 1.
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/initial-scale: "0"
        # Limit scaling to 100 pods.
        autoscaling.knative.dev/max-scale: "20"
    spec:
      containers:
        - image: 192.168.10.82:5000/front-end:v2.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          name: front-end
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - "true"
