apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: target-detector-2
spec:
  template:
    metadata:
      annotations:
        # Knative concurrency-based autoscaling (default).
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Target 10 requests in-flight per pod.
        autoscaling.knative.dev/target: "1"
        # Disable scale to zero with a min scale of 1.
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/initial-scale: "0"
        # Limit scaling to 100 pods.
        autoscaling.knative.dev/max-scale: "2"
        autoscaling.knative.dev/target-utilization-percentage: "100"
        autoscaling.knative.dev/window: "6s"
#        autoscaling.knative.dev/scale-down-delay: "1m"
    spec:
      containerConcurrency: 1
      responseStartTimeoutSeconds: 3600
      nodeSelector:
        kubernetes.io/hostname: knode2
      containers:
        - image: 192.168.10.82:5000/target-detector:v4.0
          ports:
            - containerPort: 4001
          imagePullPolicy: IfNotPresent
          name: target-detector
          volumeMounts:
            - mountPath: /home/data/
              name: reid
      volumes:
        - name: reid
          persistentVolumeClaim:
            claimName: reid-pvc