apiVersion: v1
kind: PersistentVolume
metadata:
  name: reid-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /root/pjp/nfs/reid
    server: 192.168.10.82