apiVersion: v1
kind: PersistentVolume
metadata:
  name: reid-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: <path>
    server: <ip>
